# Configuration LDAP
Covetel::LDAP: 
   host: localhost
   base: dc=iutai,dc=tec,dc=ve
   base_personas: ou=Personas,dc=iutai,dc=tec,dc=ve
   base_grupos: ou=Grupos,dc=iutai,dc=tec,dc=ve
   base_mantenimiento: ou=Mantenimiento,dc=iutai,dc=tec,dc=ve
   usuario_mantenimiento: cn=Usuario Mantenimiento
   grupo_mantenimiento: cn=Grupo Mantenimiento
   dn: cn=admin,dc=iutai,dc=tec,dc=ve
   password: elpassword
   start_tls: 0
   entry_class: Covetel::LDAP::Person
   connection_class: Covetel::LDAP
